env:
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  # '@typescript-eslint/no-non-null-assertion': on
  require-jsdoc: error
  complexity:
    - warn
    - 11
  consistent-return: error
  camelcase: error
  yoda:
    - error
    - never
  curly:
    - error
    - all
  dot-notation:
    - error
    - allowKeywords: true
  indent:
    - error
    - 4
  space-before-function-paren:
    - error
    - never
  padded-blocks:
    - error
    - never
  # prefer-arrow-callback:
  #   - allow
  #   - allowNamedFunctions: true
  func-names: error

  max-len:
    - error
    - 79
  max-statements:
    - error
    - 100
  # max-statements-per-line:
  #   - error
  #   - 1
  max-depth:
    - error
    - 3
  max-nested-callbacks:
    - error
    - 5

  eol-last:
    - error
    - always

  no-multiple-empty-lines:
    - error
    - max: 2
      maxEOF: 0
      maxBOF: 0

  no-console: warn
  no-nested-ternary: warn

  no-var: error
  no-eval: error
  no-lonely-if: error
  no-unneeded-ternary: error
  no-use-before-define: error
  no-trailing-spaces: error

  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - single
  semi:
    - error
    - never
